---
language: python
python: "2.7"
# Use the docker-enabled hosts
sudo: true
services:
  - docker
env:
  global:
    - UMD_VERSION=3
    - UMD_VERSION=4
# Install all the things
addons:
  apt:
    packages:
      - python-pip
      - ruby
      - ruby-dev
      - rubygems
install:
  # Install ansible and testing framework
  - pip install molecule docker
  - gem install inspec
before_script:
  - ansible-galaxy install -r requirements.yml
  - inspec supermarket exec brucellino/ansible-fashion-police
script:
  - molecule test -s $UMD_VERSION
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  