---
language: python
python:
  - '2.7'
  - '3.6'
sudo: true
services:
  - docker
env:
  matrix:
    - UMD_VERSION=default
    - UMD_VERSION=umd4
  global:
    - TEST_ROLE_PATH=$PWD/
    - GITHUB_REPO=ansible-role-umd
addons:
  apt:
    packages:
      - python-pip
      - ruby
      - ruby-dev
      - ruby-full
install:
  - pip install -r requirements.txt
  - gem update --system
  - gem install httparty awesome_print inspec
before_script:
  - CONTROLS=("'Travis'" "'Meta'" "'Ansible main YAML files'" "'Ansible Skeleton Directories'") inspec supermarket exec brucellino/ansible-fashion-police --controls=${CONTROLS[*]}
  - GITHUB_REPO=$TRAVIS_SLUG inspec exec supermarket exec brucellino/black-panther
script:
  - molecule dependency -s $UMD_VERSION
  - molecule lint -s $UMD_VERSION
  - molecule syntax -s $UMD_VERSION
  - molecule converge -s $UMD_VERSION
  - molecule verify -s $UMD_VERSION
after_success:
  # push to Travis
  - docker commit umd-centos7 quay.io/egi/umd4:centos7
  - docker commit umd-centos6 quay.io/egi/umd4:centos6
  - echo $TRAVIS_PULL_REQUEST
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker login -u="egi+packerbot" -p=${QUAY_PASSWORD} quay.io ; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push quay.io/egi/umd4:centos6 ; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push quay.io/egi/umd4:centos7 ; fi'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: RkOAWp4IZX5Dj57+GZnt0r9KLuMvdAZMi6b7+n9n6GR41NhnlGTYgNfyEx9ONMZGkdJKhKnHoX4BF4QQ2EJWKxXk7PySaMb2qEOI1xKeH9to0hfsCoV5lwQrdyVD8f+Scf4wS47+1AOPLS2ZkB3Kh1Ggqg9oTirxGecunl7hOt9i3+LlczTY68E05heZmc6yTayNCj3D6bP5GvSS9RyfokFIxd7nxV45EHQDeVf8VRmgwiYEklJSz0nRD697UvolYvnwPbVmaR7xJVRaDGoWHAIADx9Xmyq3u2qw3GSnxTlbAxpKiuYzbDbpr/QYEOY+5z/Zg+ZZutybTBShczd8ZsruoMh0KWDN9BcTyak6sg/Zx15LyfwcCnqfHBF5Pal2Gi2LHPISulL9UMIrpKoOtKfV4O54GQaSZ4Pam1fSyVGBIo5WFp6mcx+1I7NYmGGiwYcrnQA101/B31hP9mabMN2YMrA3hGSQ9HbIrKcG6FooH6PBk6jv3bWQtwSEabulxhgBu01X57bre+BB2QlQorStYBQSgrUuaKDyrTq8ETdEhYxGEuadfTPf2DlIuF+nX+G0e4DVjPVbUuvArx9lClP2BiP64TuDYK4xnsksIQmIhGftCLYCvGoASnoR7YT09hAxx7QPPxdp9kBmEQl609+wWIeUO44zYJFqkzLYz6c=
