---
language: python
python: "2.7"
# Use the docker-enabled hosts
sudo: true
services:
  - docker
# Install all the things
addons:
  apt:
    packages:
      - python-pip
      - ruby
      - ruby-dev
      - rubygems
install:
  # Install ansible and testing framework
  - pip install molecule docker
  - gem install inspec
before_script: 
  - ansible-galaxy install -r requirements.yml
  - inspec exec https://github.com/EGI-Foundation/ansible-fashion-police
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
