---
language: python
python:
  - '2.7'
  - '3.6'
sudo: true
services:
  - docker
env:
  matrix:
    - UMD_VERSION=default
    - UMD_VERSION=umd4
  global:
    - TEST_ROLE_PATH=$PWD/
    - secure: J7TGwIboV4SpPDGvVrTOdsraFItt26G4p4IKgFzPu3TCxkh3hcHWm6roD+yLP7z24C6TfQq69+kDn+Eol9oUXSPVenmgHBPb/v/leSjSuGH9itAsXnE8Q9L6bl8TltrJgHg6aLBaT510nf0ZL+MYjL5ZVFr+Ve1URTzz55Oe8664d4xnb0bUIE4DPO3X8okIi62fU9GMDPYqHmmp28QSOZ24zpNKvoENVvDE9s+SVTSMHlWmVvTdJfs2HmJJACnxcuDJK0Oji0fzwS31QoxNsACJz0khB7dVRMwkPFYjEWUr+ikdhkv8KR7hAC207dr8rCndiNGrLMGeQ9eHfV+depFOBPCtQpNEIr/TBGuX43kez/Vu7YCPwLV3cDCo8kdJP/hhOahP9A5XjS51N5Yck/9eahHiDLMzoqohc4tt48b+ZrJRCS2tfeLtkQA31wvPKs6ZtRGd9Eq6UWaWm0gQ1QKj5ZUd8sMvSAV5k3TeXLDemffAyxIZRgMr6hTSScmzRUwJNziidGhmwa5Oljmn3v6Wkue5eRxdhs/D92nrOMgJnnqTLyaIEL3O7ri+Fzg/fJ0QMJuVrO7tWg1hbaMYlzDQ2UyOw+DbzG/l2WmxVjMerynNUPo5KiGW8l6HxFa4T8HX0NwpsyO2JoGCe/1aLlWd0jlHh6mPRrKqTm2iO78=
    - CONTROLS=("'Travis'" "'Meta'" "'Ansible main YAML files'" "'Ansible Skeleton Directories'")
    - GITHUB_REPO=ansible-role-umd
addons:
  apt:
    packages:
      - python-pip
      - ruby
      - ruby-dev
      - ruby-full
install:
  - pip install -r requirements.txt
  - gem update --system
  - gem install httparty awesome_print inspec
before_script:
  - inspec supermarket exec brucellino/ansible-fashion-police --controls=${CONTROLS[*]}
script:
  - molecule dependency -s $UMD_VERSION
  - molecule lint -s $UMD_VERSION
  - molecule syntax -s $UMD_VERSION
  - molecule converge -s $UMD_VERSION
  - molecule verify -s $UMD_VERSION
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: RkOAWp4IZX5Dj57+GZnt0r9KLuMvdAZMi6b7+n9n6GR41NhnlGTYgNfyEx9ONMZGkdJKhKnHoX4BF4QQ2EJWKxXk7PySaMb2qEOI1xKeH9to0hfsCoV5lwQrdyVD8f+Scf4wS47+1AOPLS2ZkB3Kh1Ggqg9oTirxGecunl7hOt9i3+LlczTY68E05heZmc6yTayNCj3D6bP5GvSS9RyfokFIxd7nxV45EHQDeVf8VRmgwiYEklJSz0nRD697UvolYvnwPbVmaR7xJVRaDGoWHAIADx9Xmyq3u2qw3GSnxTlbAxpKiuYzbDbpr/QYEOY+5z/Zg+ZZutybTBShczd8ZsruoMh0KWDN9BcTyak6sg/Zx15LyfwcCnqfHBF5Pal2Gi2LHPISulL9UMIrpKoOtKfV4O54GQaSZ4Pam1fSyVGBIo5WFp6mcx+1I7NYmGGiwYcrnQA101/B31hP9mabMN2YMrA3hGSQ9HbIrKcG6FooH6PBk6jv3bWQtwSEabulxhgBu01X57bre+BB2QlQorStYBQSgrUuaKDyrTq8ETdEhYxGEuadfTPf2DlIuF+nX+G0e4DVjPVbUuvArx9lClP2BiP64TuDYK4xnsksIQmIhGftCLYCvGoASnoR7YT09hAxx7QPPxdp9kBmEQl609+wWIeUO44zYJFqkzLYz6c=
