---
- name: OS specific variables
  ansible.builtin.include_vars:
    "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version
    }}.yml"

- name: Fail if release is not defined
  ansible.builtin.fail:
    msg:
      "Incompatible release/OS combination. Please check 'release' variable and
      supported OS"
  when: (release is not defined) or (release_url[release] is not defined)

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family| lower }}.yml"

- name: Download verification repository files
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ sources_dir }}"
  with_items: "{{ verification_repofile|default([]) }}"
  when: verification_repofile is defined

- name: Set up IGTF repository
  ansible.builtin.import_tasks: igtf.yml
  tags:
    - certificates

- name: Run baseline
  ansible.builtin.import_tasks: baseline.yml
# vim: set ft=yaml.ansible:
