---
- name: Ensure EPEL is present
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Ensure release package is present (RedHat)
  ansible.builtin.package:
    name: "{{ release_url[release] }}"
    state: present

- name: Ensure UMD candidate repositories are enabled
  when: enable_candidate_repo
  block:
    - name: Enable UMD candidate base
      ansible.builtin.yum_repository:
        name: "UMD-{{ release }}-candidate-base"
        description: "UMD-{{ release }} candidate - base"
        file: "UMD-{{ release }}-candidate"
        baseurl:
          "http://repository.egi.eu/sw/production/umd/candidate/{{ release }}/{{ nick }}/x86_64/base"
        protect: true
        enabled: true
        priority: 1
        gpgcheck: false
    - name: Enable UMD candidate updates
      ansible.builtin.yum_repository:
        name: "UMD-{{ release }}-candidate-updates"
        description: "UMD-{{ release }} candidate - updates"
        file: "UMD-{{ release }}-candidate"
        baseurl:
          "http://repository.egi.eu/sw/production/umd/candidate/{{ release }}/{{ nick }}/x86_64/updates"
        protect: true
        enabled: true
        priority: 1
        gpgcheck: false

- name: Ensure yum-utils is present
  ansible.builtin.package:
    name: yum-utils
    state: present
  when: enable_testing_repo or enable_untested_repo

# these tasks are not idempotent - they should be replaced with some "replace" tasks, in a block
- name: Enable UMD testing repository
  ansible.builtin.command: yum-config-manager --enable UMD-*-testing
  when: enable_testing_repo

- name: Enable UMD untested repository
  ansible.builtin.command: yum-config-manager --enable UMD-*-untested
  when: enable_untested_repo
