---
- name: Ensure EPEL is present
  ansible.builtin.package:
    name: epel-release
    state: present

- name: "Import UMD GPG keys"
  ansible.builtin.rpm_key:
    state: "present"
    key: "{{ item }}"
  loop:
    - "https://repository.egi.eu/sw/production/umd/UMD-5-RPM-PGP-KEY"
    - "https://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY"

- name: Ensure release package is present (RedHat)
  ansible.builtin.package:
    name: "{{ release_url[release] }}"
    state: present

- name: Add UMD base candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-base"
    description: "UMD-{{ release }} candidate - base"
    file: "UMD-{{ release }}-candidate"
    baseurl: "https://repository.egi.eu/software/umd/{{ release }}/{{ nick }}/x86_64/base" 
    protect: yes
    enabled: yes
    priority: 1
    gpgcheck: no
  when: enable_candidate_repo

- name: Add UMD updates candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-updates"
    description: "UMD-{{ release }} candidate - updates"
    file: "UMD-{{ release }}-candidate"
    baseurl: "https://repository.egi.eu/software/umd/{{ release }}/{{ nick }}/x86_64/updates" 
    protect: yes
    enabled: yes
    priority: 1
    gpgcheck: no
  when: enable_candidate_repo

- name: Ensure yum-utils is present
  ansible.builtin.package:
    name: yum-utils
    state: present
  when: enable_testing_repo

# these tasks are not idempotent - they should be replaced with some "replace" tasks, in a block
- name: Enable UMD testing repository
  ansible.builtin.command: yum-config-manager --enable UMD-*-testing
  when: enable_testing_repo
