---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: umd3
verifier:
  name: testinfra
  lint:
    name: flake8
