---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: umd-centos7
    image: quay.io/centos/centos:7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: yaml, stdout, profile_tasks
      stdout_callback: yaml
      bin_ansible_callbacks: True
      nocolor: False
      force_color: True
scenario:
  name: default
verifier:
  name: testinfra
  options:
    n: 2
    color: true
