---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: umd-centos7
    image: centos:7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: yaml, stdout,profile_tasks
      stdout_callback: yaml
      bin_ansible_callbacks: True
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    n: 2
  lint:
    name: flake8
