---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: centos6
    image: centos:6
    # - name: trusty
    #   image: ubuntu:trusty
    # - name: xenial
    #   image: ubuntu:xenial
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: yaml,slack, stdout,profile_roles
      stdout_callback: yaml
      bin_ansible_callbacks: True
    callback_slack:
      channel: '#random'
      username: opsbot
      webhook_url: https://hooks.slack.com/services/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
      verbose: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
