---
name: Run molecule tests

on:
  push:
  pull_request:

jobs:
  molecule:
    name: Run molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        umd_version:
          - default
          - umd4
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "${{ github.repository }}"
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.umd_version }}
        env:
          ANSIBLE_FORCE_COLOR: "1"
