---
name: Run molecule tests

on:
  push:
  pull_request:

jobs:
  molecule:
    name: Run molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        umd_version:
          - default
          - umd5
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: "Install python dependencies"
        run: |
          pip install -r requirements.txt
        working-directory: "${{ github.repository }}"
      - name: "Run molecule manually"
        run: |
          molecule --debug test --scenario-name ${{ matrix.umd_version }}
        working-directory: "${{ github.repository }}"
        env:
          ANSIBLE_FORCE_COLOR: "1"
          PY_COLORS: "1"
      # XXX: Replaced by manual run for now, pytest is not working
      # See https://github.com/gofrolist/molecule-action/issues/245
      # - name: Molecule
      #   uses: gofrolist/molecule-action@v2
      #   with:
      #     molecule_options: --debug
      #     molecule_command: test
      #     molecule_args: --scenario-name ${{ matrix.umd_version }}
      #     molecule_working_dir: "${{ github.repository }}"
      #   env:
      #     ANSIBLE_FORCE_COLOR: "1"
      #     PY_COLORS: "1"
