---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Create packages and release

on:
  push:
  pull_request:

# FIXME shoudl only run on tags
# on:
#   push:
#     tags:
#       - "v*"

# https://github.com/marketplace/actions/push-to-registry
jobs:
  publish:
    name: Build centOS 7 RPMs
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build umd4-centos7 image with molecule
        id: build-image
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: create
          molecule_args: --scenario-name umd4
          molecule_working_dir: "${{ github.repository }}"
        env:
          ANSIBLE_FORCE_COLOR: "1"

      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: umd4
          tags: centos7
          registry: quay.io/egi
          username: egi+egi_github
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
