---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Release a new version, publish artefacts

on:
  push:
  pull_request:

# FIXME shoudl only run on tags
# on:
#   push:
#     tags:
#       - "v*"

# https://github.com/marketplace/actions/push-to-registry
jobs:
  publish:
    name: Build UMD4 for CentOS 7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build umd4-centos7 image with molecule
        id: build-image
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: create
          molecule_args: --scenario-name umd4
        env:
          ANSIBLE_FORCE_COLOR: "1"

      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Check available images
        run: |
          docker commit umd-centos7 quay.io/egi/umd4:centos7
          echo "${{ secrets.QUAY_REGISTRY_PASSWORD }}" | docker login -u="egi+egi_github" --password-stdin quay.io
          docker push quay.io/egi/umd4:centos7

      ## Publish role to ansible galaxy
