# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# XXX: CentOS 7 got archived
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum makecache fast \
  && yum update -y \
  && yum install -y python python3 sudo yum-plugin-ovl bash \
  && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
  && yum clean all
