---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: centos6
    image: centos:6
  - name: trusty
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: umd4
verifier:
  name: testinfra
  options:
    nagios: true
  lint:
    name: flake8
