---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: umd-centos7
    image: quay.io/centos/centos:7
provisioner:
  name: ansible
scenario:
  name: umd4
verifier:
  name: testinfra
  options:
    n: 2
    nagios: true
    color: true
