---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: umd-centos7
    image: quay.io/centos/centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: umd4
verifier:
  name: testinfra
  options:
    n: 2
    nagios: true
  lint:
    name: flake8
